#!/usr/bin/env node
/**
 * Merge hand-curated text prompts (tools/text-prompts.json) into the live
 * data/prompts.js without running the full photo pipeline (no Telegram
 * export / sharp needed). Also writes /p/<id>/ share pages for them.
 *   Run: node tools/sync-text.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadTextPrompts, coverSVG, TEXT_ID_MIN } from './text-data.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const DATA_PATH = path.join(ROOT, 'data', 'prompts.js');
const SHARE_DIR = path.join(ROOT, 'p');
const SITE = 'https://mohsen-niksirat.github.io/promptopia/';

const escHtml = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function sharePageHTML(o) {
  const excerpt = o.variants[0].text.replace(/\s+/g, ' ').slice(0, 160);
  const imgUrl = SITE + o.img;
  const target = SITE + '#p' + o.id;
  return `<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8">
<title>${escHtml(o.t.fa)} · پرامپتوپیا</title>
<meta name="description" content="${escHtml(excerpt)}">
<meta property="og:type" content="website">
<meta property="og:title" content="${escHtml(o.t.fa)} — پرامپتوپیا | ${escHtml(o.t.en)}">
<meta property="og:description" content="${escHtml(excerpt)}…">
<meta property="og:image" content="${imgUrl}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${escHtml(o.t.fa)} — پرامپتوپیا">
<meta name="twitter:description" content="${escHtml(excerpt)}…">
<meta name="twitter:image" content="${imgUrl}">
<link rel="canonical" href="${target}">
<meta http-equiv="refresh" content="0; url=${target}">
<script>location.replace('${target}');</script>
</head>
<body><p>در حال انتقال… <a href="${target}">${escHtml(o.t.fa)}</a></p></body>
</html>
`;
}

/* 1. load current data */
globalThis.window = {};
eval(fs.readFileSync(DATA_PATH, 'utf8'));
const data = globalThis.window.PROMPTOPIA_DATA;

/* 2. upsert text prompts (replace any previously-synced ones) */
const textPrompts = loadTextPrompts();
if (!textPrompts.length) {
  console.log('no text prompts found in tools/text-prompts.json');
  process.exit(0);
}
const photoPrompts = data.prompts.filter((p) => Number(p.id) < TEXT_ID_MIN);
const keptText = new Set(textPrompts.map((p) => p.id));
const merged = [
  ...photoPrompts,
  ...textPrompts,
  ...data.prompts.filter((p) => Number(p.id) >= TEXT_ID_MIN && !keptText.has(p.id)),
];
merged.sort((a, b) => (b.date || '').localeCompare(a.date || ''));

/* 3. generate per-prompt cover art (text prompts have no photos) */
const IMG_DIR = path.join(ROOT, 'assets', 'img');
fs.mkdirSync(IMG_DIR, { recursive: true });
for (const p of textPrompts) {
  fs.writeFileSync(path.join(IMG_DIR, `t-${p.id}.svg`), coverSVG(p.id, p.cat));
}

/* 4. write data back */
fs.writeFileSync(
  DATA_PATH,
  '/* Generated by tools/build.mjs - do not edit by hand */\nwindow.PROMPTOPIA_DATA = ' +
    JSON.stringify({ generatedAt: data.generatedAt, prompts: merged }) +
    ';\n'
);

/* 5. share pages for text prompts */
let pages = 0;
for (const p of textPrompts) {
  const dir = path.join(SHARE_DIR, String(p.id));
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), sharePageHTML(p));
  pages++;
}

const catCount = {};
for (const p of textPrompts) catCount[p.cat] = (catCount[p.cat] || 0) + 1;
console.log(`merged ${textPrompts.length} text prompts -> data/prompts.js (total ${merged.length}); wrote ${pages} share pages`);
console.log('text mix:', catCount);